### PR TITLE
fix_crash_on_second_launch -> dev

### LINKED ISSUE #30: Fix crash on second launch

### PR DESCRIPTION
**Pull request by Beafowl-Pull**
Fix crash on second job launch

### CODE REVIEW

File: jenkins/deploy.sh [hunk 1]
```diff
@@ -56,6 +56,9 @@ function detect_language() {
             continue
         fi
     done
+    if [[ -f "Makefile" && -f "CMakeLists.txt" ]]; then
+      language_detected=("cpp")
+    fi
     if [[ -f "Makefile" && $(find . -type f -name "*.bf") != "" ]]; then
```
Comment (romainpanno) [inline jenkins/deploy.sh]: Use is_brainfuck no?

**Review by romainpanno — CHANGES_REQUESTED** [review]

**Review by romainpanno — APPROVED** [review]

**Review by romainpanno — APPROVED** [review]
